Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -43,7 +43,8 @@ jobs:
         run: |
           git clone https://github.com/openssl/openssl.git
           cd openssl
-          git checkout openssl-1.1.1w
+          git checkout OpenSSL_1_1_1w
+
           export ANDROID_NDK_HOME=/opt/ndk
           export PATH=/opt/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
           export CC=aarch64-linux-android34-clang
@@ -60,7 +61,7 @@ jobs:
           make -j$(nproc)
           make install_sw install_ssldirs
 
-          ls -lh /opt/openssl-android/lib/libcrypto.a /opt/openssl-android/lib/libssl.a
+          ls -lh /opt/openssl-android/lib/libcrypto.a /opt/openssl-android/lib/libssl.a || true
 
       - name: Cross-compile libuv for Android arm64 (static)
         run: |
@@ -86,6 +87,7 @@ jobs:
           SRC_FILE="bind-${VERSION}.tar.xz"
           URL="https://ftp.isc.org/isc/bind9/\( {VERSION}/ \){SRC_FILE}"
           wget -c "$URL"
+          if [ ! -s "$SRC_FILE" ]; then echo "Download failed"; exit 1; fi
           tar xf "$SRC_FILE"
           mv "bind-${VERSION}" bind9-source
 
